// Auto-generated by CWY (stub only - implement logic)
import * as extension from "../vscode-extension/src/extension";

export function registerExtension() {
  // TODO: Connect extension to your application
  // This stub ensures the module is reachable in the graph
  console.log("extension registered");
}
