// Auto-generated by CWY (stub only - implement logic)
import * as index from "../schema/index";

export function registerIndex() {
  // TODO: Connect index to your application
  // This stub ensures the module is reachable in the graph
  console.log("index registered");
}
