// Auto-generated by CWY (stub only - implement logic)
import * as memory from "../memory/memory";

export function registerMemory() {
  // TODO: Connect memory to your application
  // This stub ensures the module is reachable in the graph
  console.log("memory registered");
}
