// Auto-generated by CWY (stub only - implement logic)
import * as overview from "../engines/overview/overview";

export function registerOverview() {
  // TODO: Connect overview to your application
  // This stub ensures the module is reachable in the graph
  console.log("overview registered");
}
