// Auto-generated by CWY (stub only - implement logic)
import * as search from "../engines/search/search";

export function registerSearch() {
  // TODO: Connect search to your application
  // This stub ensures the module is reachable in the graph
  console.log("search registered");
}
