// Auto-generated by CWY (stub only - implement logic)
import * as types from "../schema/types.js";

export function registerTypes() {
  // TODO: Connect types to your application
  // This stub ensures the module is reachable in the graph
  console.log("types registered");
}
